/**
 * Language data for PFinalClub Games
 * Contains translations for all UI elements in Chinese and English
 */

const languages = {
    zh: {
        'siteName': 'PFinalClub Games',
        'nav.home': '首页',
        'nav.allGames': '全部游戏',
        'nav.leaderboard': '排行榜',
        'nav.about': '关于我们',
        'hero.title': '欢迎来到 PFinalClub 游戏世界',
        'hero.subtitle': '探索我们精心挑选的小游戏合集，随时随地享受游戏的乐趣！',
        'hero.button': '开始探索',
        'games.title': '热门游戏',
        'games.hot': '热门',
        'games.new': '新游戏',
        'games.2048.title': '可爱 2048 游戏',
        'games.2048.desc': '合并数字，挑战你的大脑！看看你能否达到2048或更高。',
        'games.2048.score': '得分: 0',
        'games.2048.highScore': '最高分: 0',
        'games.2048.rules': '游戏规则：使用键盘方向键（上、下、左、右）控制卡片移动，相同的卡片会合并成一个数值更大的卡片，目标是合并出数值为 2048 的卡片。',
        'games.2048.winMessage': '恭喜你已经合并了一只宇宙无敌最可爱的猫咪',
        'games.2048.confirmButton': '确认',
        'games.snake.title': '贪吃蛇',
        'games.snake.desc': '经典的贪吃蛇游戏，控制蛇吃食物并避免碰到墙壁或自己。',
        'games.snake.score': '得分: 0',
        'games.snake.highScore': '最高分: 0',
        'games.snake.startButton': '开始游戏',
        'games.snake.pauseButton': '暂停',
        'games.snake.restartButton': '重新开始',
        'games.snake.rules': '游戏规则：使用键盘方向键（上、下、左、右）控制蛇的移动。吃到食物可以增加长度和得分，但要避免撞到墙壁或自己的身体。',
        'games.snake.gameOver': '游戏结束',
        'games.snake.finalScore': '最终得分: 0',
        'games.snake.playAgain': '再玩一次',
        'games.tetris.title': '俄罗斯方块',
        'games.tetris.desc': '经典的俄罗斯方块游戏，旋转和移动方块以完成行。',
        'games.memory.title': '记忆翻牌',
        'games.memory.desc': '测试你的记忆力，找出所有匹配的卡片对。',
        'games.sudoku.title': '数独',
        'games.sudoku.desc': '填充9x9网格，使每行、每列和每个3x3方块包含数字1-9。',
        'games.minesweeper.title': '扫雷',
        'games.minesweeper.desc': '经典的扫雷游戏，避开地雷并清除所有安全区域。',
        'games.playButton': '开始游戏',
        'games.viewAll': '查看全部游戏',
        'categories.title': '游戏分类',
        'categories.puzzle': '益智游戏',
        'categories.action': '动作游戏',
        'categories.casual': '休闲游戏',
        'categories.strategy': '策略游戏',
        'footer.title': 'PFinalClub Games',
        'footer.description': '提供最好玩的在线小游戏合集，随时随地享受游戏的乐趣！',
        'footer.quickLinks': '快速链接',
        'footer.contact': '联系我们',
        'footer.contactText': '有任何问题或建议？请联系我们！',
        'footer.copyright': '© 2023 PFinalClub Games. 保留所有权利。',
        'terms': '使用条款',
        'privacy': '隐私政策',
        'cookies': 'Cookie 政策',
        'sitemap': '网站地图',
        // 关于页面翻译
        'about.title': '关于我们',
        'about.subtitle': '了解 PFinalClub Games 的故事和使命',
        'about.project_intro': '项目介绍',
        'about.project_desc': 'PFinal Club Games 是一个致力于为用户提供优质在线游戏体验的平台。我们精心挑选并开发了多款经典小游戏，让您可以随时随地享受游戏的乐趣。',
        'about.our_vision': '我们的愿景',
        'about.vision_desc': '我们希望通过简单而有趣的游戏，为用户带来轻松愉悦的休闲时光。同时，我们也在不断创新和优化，为用户提供更好的游戏体验。',
        'about.features': '特色功能',
        'about.feature_1': '多语言支持，无障碍体验',
        'about.feature_2': '经典游戏，简单操作',
        'about.feature_3': '数据本地存储，保护隐私',
        'about.feature_4': '持续更新，推陈出新',
        'about.contact_us': '联系我们',
        'about.contact_desc': '如果您有任何问题或建议，欢迎通过以下方式与我们联系：',
        'language': '语言',
        // 全部游戏页面翻译
        'games.allGames.title': '全部游戏',
        'games.allGames.subtitle': '探索我们的游戏合集，找到您喜欢的游戏并立即开始游戏！',
        'games.categories': '游戏分类',
        'games.category.all': '全部',
        'games.category.puzzle': '益智',
        'games.category.arcade': '街机',
        'games.category.strategy': '策略',
        'games.category.memory': '记忆',
        'games.category.board': '棋牌',
        'games.category.word': '文字',
        'games.category.popular': '热门',
        'games.search.placeholder': '搜索游戏...',
        'games.search.noResults': '没有找到符合条件的游戏',
        'games.comingSoon': '即将推出'
    },
    en: {
        'siteName': 'PFinalClub Games',
        'nav.home': 'Home',
        'nav.allGames': 'All Games',
        'nav.leaderboard': 'Leaderboard',
        'nav.about': 'About Us',
        'hero.title': 'Welcome to PFinalClub Games World',
        'hero.subtitle': 'Explore our curated collection of mini games and enjoy gaming anytime, anywhere!',
        'hero.button': 'Start Exploring',
        'games.title': 'Popular Games',
        'games.hot': 'Hot',
        'games.new': 'New',
        'games.2048.title': 'Cute 2048 Game',
        'games.2048.desc': 'Merge numbers and challenge your brain! See if you can reach 2048 or higher.',
        'games.2048.score': 'Score: 0',
        'games.2048.highScore': 'High Score: 0',
        'games.2048.rules': 'Game Rules: Use arrow keys (up, down, left, right) to move the tiles. When two tiles with the same number touch, they merge into one. Try to reach the 2048 tile!',
        'games.2048.winMessage': 'Congratulations! You have merged the cutest cat in the universe!',
        'games.2048.confirmButton': 'OK',
        'games.snake.title': 'Snake',
        'games.snake.desc': 'Classic snake game. Control the snake to eat food and avoid hitting walls or yourself.',
        'games.snake.score': 'Score: 0',
        'games.snake.highScore': 'High Score: 0',
        'games.snake.startButton': 'Start Game',
        'games.snake.pauseButton': 'Pause',
        'games.snake.restartButton': 'Restart',
        'games.snake.rules': 'Game Rules: Use arrow keys (up, down, left, right) to control the snake. Eat food to grow longer and score points, but avoid hitting the walls or your own body.',
        'games.snake.gameOver': 'Game Over',
        'games.snake.finalScore': 'Final Score: 0',
        'games.snake.playAgain': 'Play Again',
        'games.tetris.title': 'Tetris',
        'games.tetris.desc': 'Classic Tetris game. Rotate and move blocks to complete rows.',
        'games.memory.title': 'Memory Cards',
        'games.memory.desc': 'Test your memory by finding all matching card pairs.',
        'games.sudoku.title': 'Sudoku',
        'games.sudoku.desc': 'Fill the 9x9 grid so each row, column, and 3x3 box contains digits 1-9.',
        'games.minesweeper.title': 'Minesweeper',
        'games.minesweeper.desc': 'Classic minesweeper game. Avoid mines and clear all safe areas.',
        'games.playButton': 'Play Now',
        'games.viewAll': 'View All Games',
        'categories.title': 'Game Categories',
        'categories.puzzle': 'Puzzle Games',
        'categories.action': 'Action Games',
        'categories.casual': 'Casual Games',
        'categories.strategy': 'Strategy Games',
        'footer.title': 'PFinalClub Games',
        'footer.description': 'Providing the best online mini games collection for you to enjoy anytime, anywhere!',
        'footer.quickLinks': 'Quick Links',
        'footer.contact': 'Contact Us',
        'footer.contactText': 'Have questions or suggestions? Contact us!',
        'footer.copyright': '© 2023 PFinalClub Games. All rights reserved.',
        'terms': 'Terms of Use',
        'privacy': 'Privacy Policy',
        'cookies': 'Cookie Policy',
        'sitemap': 'Sitemap',
        // About page translations
        'about.title': 'About Us',
        'about.subtitle': 'Learn about PFinalClub Games story and mission',
        'about.project_intro': 'Project Introduction',
        'about.project_desc': 'PFinal Club Games is a platform dedicated to providing quality online gaming experiences. We carefully select and develop classic mini games for you to enjoy anytime, anywhere.',
        'about.our_vision': 'Our Vision',
        'about.vision_desc': 'We aim to bring relaxing and enjoyable leisure time through simple and fun games. Meanwhile, we continuously innovate and optimize to provide better gaming experiences.',
        'about.features': 'Key Features',
        'about.feature_1': 'Multi-language support for barrier-free experience',
        'about.feature_2': 'Classic games with simple controls',
        'about.feature_3': 'Local data storage to protect privacy',
        'about.feature_4': 'Continuous updates with new content',
        'about.contact_us': 'Contact Us',
        'about.contact_desc': 'If you have any questions or suggestions, please contact us through the following channels:',
        'language': 'Language',
        // All Games page translations
        'games.allGames.title': 'All Games',
        'games.allGames.subtitle': 'Explore our game collection, find your favorite and start playing right away!',
        'games.categories': 'Game Categories',
        'games.category.all': 'All',
        'games.category.puzzle': 'Puzzle',
        'games.category.arcade': 'Arcade',
        'games.category.strategy': 'Strategy',
        'games.category.memory': 'Memory',
        'games.category.board': 'Board',
        'games.category.word': 'Word',
        'games.category.popular': 'Popular',
        'games.search.placeholder': 'Search games...',
        'games.search.noResults': 'No games found matching your criteria',
        'games.comingSoon': 'Coming Soon'
    }
};

// Helper functions for game names
function getChineseGameName(type) {
    const names = {
        'snake': '贪吃蛇',
        'tetris': '俄罗斯方块',
        'memory': '记忆翻牌',
        'sudoku': '数独',
        'minesweeper': '扫雷'
    };
    return names[type] || type;
}

function getEnglishGameName(type) {
    const names = {
        'snake': 'Snake',
        'tetris': 'Tetris',
        'memory': 'Memory Cards',
        'sudoku': 'Sudoku',
        'minesweeper': 'Minesweeper'
    };
    return names[type] || type;
}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { languages, getChineseGameName, getEnglishGameName };
}
